version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "getting_prices_api"
      MYSQL_USER: "kassio"
      MYSQL_PASSWORD: "kassio"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080