version: '3.1'

services:

  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "getting_prices_api"
      MYSQL_USER: "kassio"
      MYSQL_PASSWORD: "kassio"
